variables:
  # This will suppress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dhttps.protocols=TLSv1.2 -Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd` are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  KEY_FILE_NAME: "bbqb-prd-99d80e3729ad"

stages:
  - build
  - deploy

cache:
  paths:
    - .m2/repository

before_script:
  - chmod +x mvnw

build:
  stage: build
  image: java:8
  before_script:
    - echo ${SERVICE_ACCOUNT} > /tmp/$KEY_FILE_NAME.json
  script: ./mvnw $MAVEN_CLI_OPTS package appengine:stage
  artifacts:
    paths:
      - target/appengine-staging

.google_cloud_auth: &google_cloud_auth
  image: google/cloud-sdk
  before_script:
    - echo ${SERVICE_ACCOUNT} > /tmp/$KEY_FILE_NAME.json
    - gcloud auth activate-service-account --key-file /tmp/$KEY_FILE_NAME.json

deploy:prd:
  <<: *google_cloud_auth
  only:
    - master
  stage: deploy
  environment: Production
  script:
    - gcloud config set project bbqb-prd --quiet
    - gcloud app deploy target/appengine-staging --version $CI_COMMIT_SHORT_SHA